version: '3.7'
services:
  api:
    image: game-utils-api
    networks:
      - webnet
    environment:
      - CORS_ORIGINS=https://jb.joshwolfe.ca
    deploy:
      labels:
        - traefik.http.routers.game-utils-api.rule=Host(`api-jb.joshwolfe.ca`)
        - traefik.http.routers.game-utils-api.tls=true
        - traefik.http.services.game-utils-api-service.loadbalancer.server.port=80
      placement:
        constraints:
          - node.hostname == shirleytemple
  ui:
    image: game-utils-ui
    networks:
      - webnet
    deploy:
      labels:
        - traefik.http.routers.game-utils-ui.rule=Host(`jb.joshwolfe.ca`)
        - traefik.http.routers.game-utils-ui.tls=true
        - traefik.http.services.game-utils-ui-service.loadbalancer.server.port=80
      placement:
        constraints:
          - node.hostname == shirleytemple

networks:
  webnet:
    external: true
