name: build-and-push-docker
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - uses: docker/build-push-action@v2
        name: 'Build and push API'
        with:
          context: './api'
          file: './api/Dockerfile'
          push: true
          tags: ghcr.io/wolfecub/game-utils-api:latest

      - uses: docker/build-push-action@v2
        name: 'Build and push UI'
        with:
          context: './ui'
          file: './ui/Dockerfile'
          push: true
          tags: ghcr.io/wolfecub/game-utils-ui:latest
